"""empty message

Revision ID: 6401cc32fe2a
Revises: a6308f68c9a5
Create Date: 2023-03-12 18:02:31.813745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6401cc32fe2a'
down_revision = 'a6308f68c9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_album', schema=None) as batch_op:
        batch_op.drop_constraint('photo_album_property_type_id_fkey', type_='foreignkey')
        batch_op.drop_column('property_type_id')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('bathrooms',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('bathrooms',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('photo_album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('photo_album_property_type_id_fkey', 'property_type', ['property_type_id'], ['id'])

    # ### end Alembic commands ###
