"""empty message

Revision ID: 801ffc13bfed
Revises: 
Create Date: 2023-03-11 22:05:08.822527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801ffc13bfed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('property_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('property_type_id', sa.Integer(), nullable=True),
    sa.Column('main_photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('property_type_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('photo_album_id', sa.Integer(), nullable=True),
    sa.Column('main_photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['photo_album_id'], ['photo_album.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    op.drop_table('photo_album')
    op.drop_table('photos')
    op.drop_table('property_type')
    # ### end Alembic commands ###
