"""empty message

Revision ID: a6308f68c9a5
Revises: 801ffc13bfed
Create Date: 2023-03-11 22:05:24.958414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6308f68c9a5'
down_revision = '801ffc13bfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_album_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'photo_album', ['photo_album_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('photo_album_id')

    # ### end Alembic commands ###
